### ISSUE TITLE
Can't build wheel with somoclu and pip 23.1

### ISSUE THREAD

**Issue by OliviaLynn** [peterwittek/somoclu#169]
Pip's recent update to 23.1 is now preventing users from building wheels that include somoclu.

I've recreated the most minimal version in an empty repository with the workflow:
```
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy
        pip install somoclu
```
This workflow fails [[link]](https://github.com/OliviaLynn/somoclu-pip-test/actions/runs/4738992244), but on removing the line to upgrade pip, the workflow runs successfully [[link]](https://github.com/OliviaLynn/somoclu-pip-test/actions/runs/4739005769).
